---
# Create a launch config and app autoscaling group
# New launch config is created anytime a new ami id shows up in vars/ami_current.yml

- hosts: aws-deploy-rolling
  gather_facts: False
  vars:
    tmp_desired_capacity: "{{ asg_desired_capacity + batch_size }}"
    tmp_min_size: "{{ asg_min_size + batch_size }}"
    tmp_max_size: "{{ asg_max_size + batch_size }}"
  vars_files:
  - vars/ami_current.yml
  roles:
  - aws_core
  tasks:
  - name: create launch config
    ec2_lc:
      name: "{{ lc_name }}"
      image_id: "{{ image_id }}"
      key_name: "{{ key_name }}"
      region: "{{ region }}"
      security_groups: "{{ lc_security_groups }}"
      instance_type: "{{ instance_type }}"
      assign_public_ip: yes
    tags: launch_config

  - name: create autoscale group or assign new launch config
    ec2_asg:
      name: "{{ asg_group_name }}"
      health_check_period: 60
      load_balancers: "{{ load_balancers }}"
      health_check_type: ELB
      availability_zones: "{{ availability_zones | join(',')}}"
      launch_config_name: "{{ lc_name }}"
      min_size: "{{ asg_min_size }}"
      max_size: "{{ asg_max_size }}"
      desired_capacity: "{{ asg_desired_capacity }}"
      region: "{{ region }}"
      replace_all_instances: yes
      vpc_zone_identifier: "{{ asg_subnets | join(',') }}"
    until: asg_result.viable_instances|int >= asg_desired_capacity|int
    delay: 10
    retries: 120
    register: asg_result
    tags: autoscale_group
